# Generated by Django 4.1.3 on 2022-11-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_subtask_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='task',
        ),
    ]
