# Generated by Django 4.1.3 on 2022-12-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_subtask_post_subtaskbobn1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='taskAlice',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
