# Generated by Django 4.1.3 on 2022-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_subtaskcesar_post_taskbobn3_post_taskcesarn1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
