# Generated by Django 4.1.3 on 2022-12-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_contributor_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('TODO', 'TD')], default='TD', max_length=20, null=True),
        ),
    ]
