# Generated by Django 4.1.3 on 2022-12-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_status_post_statustask1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='statusTask2',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='statusTask3',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='statusTask4',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='statusTask5',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='statusTask6',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subtasSubTask1',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subtasSubTask2',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='statusTask1',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
    ]
