# Generated by Django 4.1.3 on 2022-12-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_statustask2_remove_post_statustask3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
        migrations.RemoveField(
            model_name='post',
            name='statusTask1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtasSubTask1',
        ),
    ]
