# Generated by Django 4.1.3 on 2022-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_post_password_remove_post_statustask1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtaskBobN1',
            new_name='tasks_subtasks_status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taskBobN1',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
