# Generated by Django 4.1.3 on 2022-12-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_rename_tasks_subtasks_status_post_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tasks_subtasks',
            new_name='tasks_subtasks_status',
        ),
    ]
