# Generated by Django 4.1.3 on 2022-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_post_contributor_post_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contributor',
            field=models.CharField(max_length=100),
        ),
    ]
