# Generated by Django 4.1.3 on 2023-01-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
