# Generated by Django 4.1.3 on 2023-01-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_rename_message_post_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
