# Generated by Django 4.1.3 on 2022-12-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_content_post_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtask',
            new_name='subtaskBobN1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='task',
            new_name='taskBobN1',
        ),
    ]
