# Generated by Django 4.1.3 on 2022-12-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
    ]
