# Generated by Django 4.1.3 on 2022-12-08 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_post_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contributor',
            field=models.ManyToManyField(related_name='contrib', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('TD', 'TODO')], default='TODO', max_length=20, null=True),
        ),
    ]
