# Generated by Django 4.1.3 on 2022-12-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='statusTask1',
        ),
    ]
