# Generated by Django 4.1.3 on 2022-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_statustask2_post_statustask3_post_statustask4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtasSubTask4',
            field=models.CharField(choices=[('TO DO', 'TO DO'), ('IN PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE'), ('IN REVISION', 'IN REVISION')], default='TO DO', max_length=15, null=True),
        ),
    ]
