# Generated by Django 4.1.3 on 2022-12-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_subtassubtask4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtasSubTask4',
            new_name='subtasSubTask3',
        ),
    ]
