# Generated by Django 4.1.3 on 2022-12-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='statusTask2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='statusTask3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='statusTask4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='statusTask5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='statusTask6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtasSubTask2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtasSubTask3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtaskBobN2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtaskCesar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taskAlice',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taskBobN2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taskBobN3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taskCesarN1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='taskCesarN2',
        ),
    ]
