# Generated by Django 4.1.3 on 2022-12-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tasks_subtasks_status',
            field=models.TextField(max_length=100),
        ),
    ]
