# Generated by Django 4.1.3 on 2023-01-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_post_options_post_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='priority',
        ),
    ]
