# Generated by Django 4.1.3 on 2023-01-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_post_priority_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.TextField(),
        ),
    ]
